//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Human
    {
        public int id { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public string Lname { get; set; }
        public short Age { get; set; }
        public Nullable<int> DepId { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual Dep Dep { get; set; }
        public virtual Position Position1 { get; set; }
    }
}
